
# Define target output
target: prom

# You can rename the project (e.g., if you build different variants
# from the same Makefile and source tree). Ruckus will print a fat
# warning but that can be ignored...
#
#export PROJECT=MyProject

# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

# Define the Microblaze source path
#export SDK_SRC_PATH = $(PROJ_DIR)/../../../common/core/src

# Whether to use the on-board PHY (connected to the RJ-45 jack)
# or an SFP module for ethernet connectivity.
# Must be true or false
export INCLUDE_ETH_SGMII_LVDS = 1

export REMOVE_UNUSED_CODE = 1

# Using a non-standard target directory structure, 
# which requires me to define the TOP_DIR path
export TOP_DIR = $(abspath $(PWD)/../../..)

# Use top level makefile
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
