export PARALLEL_BUILD = 3
export BUILD_SCRIPT = $(PWD)/submodules/ruckus/system_build_all.mk
export SETUP_ENV    = $(PWD)/setup_env_slac.csh
export TARGET_DIRS  = $(PWD)/targets/XilinxKCU105DevBoard/Kcu105GigE/ 


# Use top level makefile
include $(BUILD_SCRIPT)
